[2024-05-07T12:05:58.910+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-07T12:05:58.957+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: git_repo_dag.list_repo_tags manual__2024-05-07T12:05:50.612664+00:00 [queued]>
[2024-05-07T12:05:58.971+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: git_repo_dag.list_repo_tags manual__2024-05-07T12:05:50.612664+00:00 [queued]>
[2024-05-07T12:05:58.972+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-07T12:05:59.009+0000] {taskinstance.py:2330} INFO - Executing <Task(GithubOperator): list_repo_tags> on 2024-05-07 12:05:50.612664+00:00
[2024-05-07T12:05:59.019+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'git_repo_dag', 'list_repo_tags', 'manual__2024-05-07T12:05:50.612664+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/git_repo_dag.py', '--cfg-path', '/tmp/tmpucur6sdu']
[2024-05-07T12:05:59.022+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask list_repo_tags
[2024-05-07T12:05:59.025+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=158) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-07T12:05:59.026+0000] {standard_task_runner.py:63} INFO - Started process 171 to run task
[2024-05-07T12:05:59.112+0000] {task_command.py:426} INFO - Running <TaskInstance: git_repo_dag.list_repo_tags manual__2024-05-07T12:05:50.612664+00:00 [running]> on host 989dff356211
[2024-05-07T12:05:59.253+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='git_repo_dag' AIRFLOW_CTX_TASK_ID='list_repo_tags' AIRFLOW_CTX_EXECUTION_DATE='2024-05-07T12:05:50.612664+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-07T12:05:50.612664+00:00'
[2024-05-07T12:05:59.254+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-07T12:05:59.312+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-07T12:05:59.327+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/github/operators/github.py", line 67, in execute
    hook = GithubHook(github_conn_id=self.github_conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/github/hooks/github.py", line 48, in __init__
    self.get_conn()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/github/hooks/github.py", line 55, in get_conn
    conn = self.get_connection(self.github_conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `github_default` isn't defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/github/operators/github.py", line 79, in execute
    raise AirflowException(f"GitHub operator error: {e}")
airflow.exceptions.AirflowException: GitHub operator error: The conn_id `github_default` isn't defined
[2024-05-07T12:05:59.336+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=git_repo_dag, task_id=list_repo_tags, run_id=manual__2024-05-07T12:05:50.612664+00:00, execution_date=20240507T120550, start_date=20240507T120558, end_date=20240507T120559
[2024-05-07T12:05:59.375+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 23 for task list_repo_tags (GitHub operator error: The conn_id `github_default` isn't defined; 171)
[2024-05-07T12:05:59.402+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-07T12:05:59.436+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-07T12:05:59.460+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
